/elevation_mapping_node:
  ros__parameters:
    subscribers:
      front_cam:
        topic_name: '/livox/lidar'
        data_type: pointcloud

    publishers:
      elevation_map_raw:
        layers: ['elevation', 'variance',]
        basic_layers: ['elevation']
        fps: 10.0
      elevation_map_filter:
        layers: ['min_filter', 'smooth', 'elevation', 'heights_body_frame']
        basic_layers: ['min_filter']
        fps: 10.0